ptu12_autoservisas/autoservisas/urls.py
from django.urls import path, include
from . import views
from .views import index, car_list, car_detail, OrderListView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("cars/", views.car_list, name="car_list"),
    path("car_detail/<int:pk>/", views.car_detail, name="car_detail"), 
    path("orders/", views.OrderListView.as_view(), name="order_list_view"),
    path("orders/<int:pk>/", views.OrderDetailView.as_view(), name="order_detail"),
    path("my_orders/", views.UserOrderEntryListView.as_view(), name="my_orders"),
    path("tinymce/", include("tinymce.urls")),
    path("profile/", include("user_profile.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

ptu12_autoservisas/ptu12_autoservisas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("autoservisas.urls"))
]

ptu12_autoservisas/autoservisas/models.py
from typing import Any, Iterable, Optional
from django.db import models
from django.utils.translation import gettext_lazy as _ 
from django.urls import reverse
from datetime import date
from django.contrib.auth import get_user_model
from tinymce.models import HTMLField

User = get_user_model()

class CarModel(models.Model):
    brand = models.CharField(_("Make"), max_length=100, db_index=True)
    model = models.CharField(_("Model"), max_length=50, db_index=True)
    year = models.IntegerField(_("Year"), null=True, blank=True, db_index=True)

    class Meta:
        ordering = ['brand', 'model']
        verbose_name = _("car model")
        verbose_name_plural = _("car models")

    def __str__(self):
        return f"{self.brand} - {self.model}"

    def get_absolute_url(self):
        return reverse("carmodel_detail", kwargs={"pk": self.pk})


class Car(models.Model):
    client = models.ForeignKey(
        User, 
        verbose_name=_("client"), 
        related_name="cars", 
        on_delete=models.CASCADE, null=True, blank=True)
    license_plate = models.CharField(_("License plate Nr."), max_length=50, db_index=True)
    model = models.ForeignKey(
        CarModel, 
        verbose_name=_("model"), 
        on_delete=models.CASCADE,
        related_name="cars")
    vin_code =  models.CharField(_("VIN code"), max_length=50, db_index=True)
    description = HTMLField(_("Description"), max_length=10000, null=True, blank=True)

    cover = models.ImageField(
        _("cover"), upload_to="autoservisas/car_covers",
        null=True, blank=True,
    )

    class Meta:
        ordering = ["model", 'license_plate']
        verbose_name = _("car")
        verbose_name_plural = _("cars")

    def __str__(self):
        return f"{self.license_plate}"

    def get_absolute_url(self):
        return reverse("car_detail", kwargs={"pk": self.pk})
    
    
class Order(models.Model):
    date = models.DateField(_("Date"), auto_now=False, auto_now_add=True, db_index=True)
    price = models.DecimalField(_("Price"), max_digits=18, decimal_places=2, default=0, null=True)
    car = models.ForeignKey(
        Car, 
        verbose_name=_("car"), 
        on_delete=models.CASCADE,
        related_name="orders")
    
    due_back = models.DateField(_("Due back"), null=True, blank=True, db_index=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
    
    class Meta:
        ordering = ['date', "id"]
        verbose_name = _("order")
        verbose_name_plural = _("orders")

    def __str__(self):
        return f"No. - {self.car} - { self.car.model.model}"

    def get_absolute_url(self):
        return reverse("order_detail", kwargs={"pk": self.pk})
    
    @property
    def client(self):
        return self.car.client

class Service(models.Model):
    name = models.CharField(_("Service Name"), max_length=150, db_index=True)
    price = models.DecimalField(_("Price"), max_digits=18, decimal_places=2, null=True)
    
    class Meta:
        ordering = ["name", "price"]
        verbose_name = _("service")
        verbose_name_plural = _("services")

    def __str__(self):
        return f"{self.name} - {self.price}"

    def get_absolute_url(self):
        return reverse("service_detail", kwargs={"pk": self.pk})


class OrderEntry(models.Model):
    service = models.ForeignKey(
        Service, 
        verbose_name=_("service"),
        related_name="order_entries", 
        on_delete=models.CASCADE, null=True)
    order = models.ForeignKey(
        Order, 
        verbose_name=_("order"),
        related_name="order_entries",
        on_delete=models.CASCADE, null=True)
    quantity = models.DecimalField(_("Quantity"),max_digits=18, decimal_places=2, default=1)
    price = models.DecimalField(_("Price"), max_digits=18, decimal_places=2, default=0)
    total = models.DecimalField(_("Total"), max_digits=18, decimal_places=2, default=0)
    
    STATUS_CHOICES = [
        ("new", "New"),
        ("processing", "Processing"),
        ("complete", "Complete"),
        ("cancelled", "Cancelled"),
    ]
    status = models.CharField(_("Status"), max_length=20, choices=STATUS_CHOICES, default="new", db_index=True)
    
    class Meta:
        ordering = ["price", "quantity"]
        verbose_name = _("order entry")
        verbose_name_plural = _("order entries")

    def __str__(self):
        return f"{self.service.name} - {self.quantity} - {self.price}"

    def get_absolute_url(self):
        return reverse("orderentry_detail", kwargs={"pk": self.pk})
    
    def get_color(self):
        colors = {
            "new": "blue",
            "processing": "orange",
            "complete": "green",
            "cancelled": "red",
        }
        default_color = "black"
        return colors.get(self.status, default_color)

    def get_status_display(self):
        return dict(self.STATUS_CHOICES).get(self.status)

    def save(self, *args, **kwargs):
        if self.price == 0:
            self.price = self.service.price
        if self.status != "cancelled":  # Skip calculating total if service is cancelled
            self.total = self.price * self.quantity
        super().save(*args, **kwargs)
        self.order.price = self.order.order_entries.exclude(status="cancelled").aggregate(models.Sum("total"))["total__sum"]
        self.order.save()

class UserOrderReview(models.Model):
    order = models.ForeignKey(
        Order,
        verbose_name=_("order"),
        on_delete=models.CASCADE,
        related_name="reviews",
    )

    reviewer = models.ForeignKey(
        User,
        verbose_name=_("reviewer"),
        on_delete=models.SET_NULL,
        related_name="user_order_review",
        null=True, blank=True,
    )   
    reviewed_at = models.DateTimeField(_("Reviewed"), auto_now_add=True)
    content = models.TextField(_("content"), max_length=4000)

    class Meta:
        ordering = ["-reviewed_at"]
        verbose_name = _("user order review")
        verbose_name_plural = _("user order reviews")

    def __str__(self):
        return f"{self.reviewed_at}: {self.reviewer}"

    def get_absolute_url(self):
        return reverse("userorderreview_detail", kwargs={"pk": self.pk})

ptu12_autoservisas/autoservisas/forms.py
from django import forms
from . import models

class OrderReviewForm(forms.ModelForm):
    class Meta:
        model = models.UserOrderReview
        fields = ("content", "order", "reviewer")
        widgets = {
            "order" : forms.HiddenInput(),
            "reviewer" : forms.HiddenInput(),
        }

ptu12_autoservisas/autoservisas/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.db.models import Q
from django.http import HttpResponse 
from django.shortcuts import render, get_object_or_404, reverse
from django.core.paginator import Paginator
from .models import Service, Car, OrderEntry, CarModel, Order
from django.views import View , generic
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from . forms import OrderReviewForm
# Create your views here.

def index(request):
    num_service = Service.objects.all().count()
    num_car = Car.objects.all().count()
    num_completed_services = OrderEntry.objects.filter(status="complete").count()

    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_service" : num_service,
        "num_car" : num_car,
        "num_completed_services" : num_completed_services,
        "num_visits" : num_visits
    }
    return render(request, "autoservisas/index.html", context)

    

def car_list(request):
    qs = Car.objects
    query = request.GET.get("query")
    if query:
        qs = qs.filter(
            Q(model__brand__istartswith=query) |
            Q(client__istartswith=query) |
            Q(model__model__istartswith=query)
            
        )
    else:
        qs = qs.all()
    paginator = Paginator(qs, 5)
    car_list = paginator.get_page(request.GET.get("page"))
    return render(request, "autoservisas/car_list.html", {
        "car_list" : car_list,
    })

def car_detail(request, pk: int):
    car_detail = get_object_or_404(Car, pk=pk)
    context = {
        "car" : car_detail
    }
    return render(request, "autoservisas/car_detail.html", context)

class OrderListView(generic.ListView):
    model = Order
    paginate_by = 5
    context_object_name = "orders"
    template_name = "autoservisas/order_list_view.html"
    
    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        query = self.request.GET.get("query")
        if query:
            qs = qs.filter(
                Q(car__client__icontains=query) |
                Q(car__license_plate__istartswith=query) |
                Q(car__vin_code__istartswith=query) |
                Q(car__model__model__icontains=query) |
                Q(car__model__brand__icontains=query)
            )
        return qs



class OrderDetailView(generic.edit.FormMixin, generic.DetailView):
    model = Order
    template_name = "autoservisas/order_detail.html"
    context_object_name = "order"
    form_class = OrderReviewForm
    
    def get_initial(self) -> Dict[str, Any]:
        initial = super().get_initial()
        initial["order"] = self.get_object()
        initial["reviewer"] = self.request.user
        return initial
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_valid(self, form: Any) -> HttpResponse:
        form.instance.order = self.get_object()
        form.instance.reviewer = self.request.user
        form.save()
        messages.success(self.request, _("Comment posted."))
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse("order_detail", kwargs={"pk":self.get_object().pk})

    def get_queryset(self):
        return super().get_queryset().prefetch_related("order_entries")
    

class UserOrderEntryListView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = "autoservisas/my_orders.html"
    paginate_by = 5

    def get_queryset(self) -> QuerySet[Any]:
        qs = super().get_queryset()
        qs = qs.filter(car__client=self.request.user)
        return qs

# @login_required
# def my_orders(request):
#     user = request.user
#     orders = Order.objects.filter(car__user_field=user)
#     return render(request, "autoservisas/my_orders.html", {"orders":orders})



 

ptu12_autoservisas/autoservisas/templates/autoservisas/car_detail.html
{% extends "base.html" %}
 {% load static %}
{% block title %} Car details {{ block.super }}{% endblock title %}
{% block content %}
<script>
    function goBack() {
        window.history.back();
    }
</script>

<h1>Car details</h1>
{% if car.cover %}
    <img class="car_covers" src="{{ car.cover.url }}">
{% else %}
    <img class="car_covers" src="{% static "autoservisas/img/no_car_img.jpg" %}"> 
{% endif %}
<a class="button" onclick="goBack()">&#10554;</a>
<p>Make & Model: {{ car.model.brand}} -  {{ car.model.model }}</p>
<p>Year: {{ car.model.year }}</p>
<p>License Plate: {{ car.license_plate }}</p>
<p>VIN Code: {{ car.vin_code }}</p>
Description: {{ car.description|safe }}

{% endblock content %}

ptu12_autoservisas/autoservisas/templates/autoservisas/car_list.html
{% extends 'base.html' %}
{% block title %} Car list {{ block.super }}{% endblock title %}
{% block content %}
<h1>Current cars in service</h1>
{% if car_list %}
{% with car_list as page_obj %}
    {% include "includes/paginator_nav.html" %}
{% endwith %}
<ul>
    {% for car in car_list %}
        <li><a href="{% url 'car_detail' car.pk %}"> {{ car.model.brand }}  -  {{ car.model.model}} </a></li>
    {% endfor %}
</ul>
{% with car_list as page_obj %}
  {% include "includes/paginator_pages.html" %}
{% endwith %}
{% else %}
    <p>No cars found</p>
{% endif %}
{% endblock content %}

ptu12_autoservisas/autoservisas/templates/autoservisas/index.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Welcome to {{ block.super }}{% endblock title %}
{% block content %}
<h1>Garage</h1>

<p>Currently available:</p>
<ul>
    <li><strong>Cars:</strong> {{ num_car }}</li>
    <li><strong>Services:</strong> {{ num_service }}</li>
    <li><strong>Completed services:</strong> {{ num_completed_services }}</li>
    <li>You're visiting us already for the <strong>{{ num_visits|ordinal }}</strong> time.
    <i class="fa-light fa-calculator fa-bounce fa-2xs"></i>
    </li>
</ul>
{% endblock content %}

ptu12_autoservisas/autoservisas/templates/autoservisas/my_orders.html
{% extends 'base.html' %}
{% block title %}My orders {{ block.super }}{% endblock title %}

{% block content %}
<h1>My orders</h1>
{% if order_list %}
<ul>
    {% for order in order_list %}
        <a href="{% url 'order_detail' order.pk %}">
            <li>
                {{ order.car.model }}</a>- Should be fixed by: {{ order.due_back }}
                {% if order.status == status and order.is_overdue %}
                    <span class="orderoverdue">OVERDUE!</span></li>
                {% endif %}
            </li>
    {% endfor %}
</ul>
{% else %}
    <p class="box box-warning">
        <p>No orders found. Please feel free to get some!</p>
    </p>
{% endif %}
{% endblock content %}

ptu12_autoservisas/autoservisas/templates/autoservisas/order_detail.html
{% extends 'base.html' %}
{% block title %} Order Details | {{ block.super }}{% endblock title %}
{% block content %}
<h1>Order No: {{ order.id }}</h1>
<ul>
    <li>Date: {{ order.date }}</li>
    <li>Car: {{ order.car.model }}</li>
    <li>Owner: {{ order.car.client }}</li>
</ul>

{% if order.order_entries.count > 0 %}

    <strong>Order Entries:</strong>
    <ul>
        {% for entry in order.order_entries.all %}
            <li>
            <strong>Service:</strong> {{ entry.service }}
            <br>
            <strong>Quantity:</strong> {{ entry.quantity }}
            </li>
            <strong>Total:</strong> {{ entry.total }}
            </li>
            <li><strong>Status:</strong> 
          {% with entry_color=entry.get_color %}
            <span style="color: {{ entry_color }}">{{ entry.get_status_display }}<br><br></span>
          {% endwith %}
        {% endfor %}
        <strong>Total service fee - {{ order.price }}&#8364;</strong>
    </ul>
{% endif %}
<h2>Commentary section</h2>
{% if user.is_authenticated %}
{% if user.is_superuser or user.is_staff or user == order.car.client %} 
    <form method="post" action="{{ request.path }}">
    <h3>Leave your comments:</h3>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Post</button>
    </form>
{% else %}
    <p class="box box-info">Only the car owner or registered users can discuss. <a href="{% url 'login' %}">Login</a> or <a href="{% url 'signup' %}">sign up</a></p>
{% endif %}
{% endif %} 
{% if order.reviews.count > 0 %}
    <ul>
        {% for review in order.reviews.all  %}
            <li>{{ review.reviewed_at }} by {{ review.reviewer }}<br>
                {{ review.content }}
            </li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock content %}

ptu12_autoservisas/autoservisas/templates/autoservisas/order_list_view.html
{% extends 'base.html' %}
{% block title %}Service Orders {{ block.super }}{% endblock title %}
{% block content %}
<h1>Service orders</h1>
<form action="" method="get">
    <input name="query" type="text" value="{{ request.GET.query }}">
    <button type="submit">&#128269;</button>
    {% if request.GET.query %}<a href="{{ request.path }}">&#10007;</a>{% endif %}
</form>
{% if orders %}
{% include  "includes/paginator_nav.html" %}
<ul>
    {% for order in orders %}
        <li><a href="{% url 'order_detail' order.pk %}">
        <strong>Car Model:</strong> {{ order.car.model.model }}</a></li>
    {% endfor %}
</ul>
{% include  "includes/paginator_pages.html" %}
{% else %}
<p>No orders found</p>
{% endif %}
{% endblock content %}